"use client";

import { CalendarDays, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { createPortal } from 'react-dom';
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';

function parse(value: string) { const [year, month, day] = value.split('-').map(Number); return year && month && day ? new Date(year, month - 1, day) : null; }
function serialize(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
export function CalendarDatePicker({ value, onChange, disabled = false, ariaLabel, allowClear = true, minDate, referenceDate, referenceLabel = 'Start date' }: { value: string; onChange: (value: string) => void; disabled?: boolean; ariaLabel: string; allowClear?: boolean; minDate?: string; referenceDate?: string; referenceLabel?: string }) {
  const initial = parse(value) ?? new Date();
  const [open, setOpen] = useState(false); const [view, setView] = useState(initial); const [mobile, setMobile] = useState(false);
  const [position, setPosition] = useState({ left: 12, top: 12, width: 320 });
  const buttonRef = useRef<HTMLButtonElement>(null); const panelRef = useRef<HTMLDivElement>(null);
  const [prevValue, setPrevValue] = useState(value);
  if (value !== prevValue) {
    setPrevValue(value);
    const selected = parse(value);
    if (selected) setView(selected);
  }
  useLayoutEffect(() => { if (!open) return; const place = () => { const rect = buttonRef.current?.getBoundingClientRect(); if (!rect) return; const isMobile = window.innerWidth < 768; setMobile(isMobile); if (isMobile) return; const width = 320; const height = 390; const top = window.innerHeight - rect.bottom >= height + 8 ? rect.bottom + 6 : Math.max(12, rect.top - height - 6); setPosition({ left: Math.min(Math.max(12, rect.left), window.innerWidth - width - 12), top, width }); }; place(); window.addEventListener('resize', place); window.addEventListener('scroll', place, true); return () => { window.removeEventListener('resize', place); window.removeEventListener('scroll', place, true); }; }, [open]);
  useEffect(() => { if (!open) return; const outside = (event: PointerEvent) => { const node = event.target as Node; if (!buttonRef.current?.contains(node) && !panelRef.current?.contains(node)) setOpen(false); }; document.addEventListener('pointerdown', outside); return () => document.removeEventListener('pointerdown', outside); }, [open]);
  const days = useMemo(() => { const offset = new Date(view.getFullYear(), view.getMonth(), 1).getDay(); const count = new Date(view.getFullYear(), view.getMonth() + 1, 0).getDate(); return [...Array(offset).fill(null), ...Array.from({ length: count }, (_, index) => index + 1)]; }, [view]);
  const selected = parse(value); const today = serialize(new Date());
  const minimum = parse(minDate ?? '');
  const referenceKey = parse(referenceDate ?? '') ? referenceDate : undefined;
  const isBeforeMinimum = (candidate: Date) => minimum ? candidate < minimum : false;
  const panel = open && typeof document !== 'undefined' ? createPortal(<>{mobile && <button type="button" className="fixed inset-0 z-[419] bg-black/55" aria-label={`Close ${ariaLabel}`} onClick={() => setOpen(false)} />}<div ref={panelRef} role="dialog" aria-label={ariaLabel} style={mobile ? undefined : position} className={`fixed z-[420] border border-[#4E4F50] bg-[#3A3B3C] p-4 ${mobile ? 'inset-x-3 bottom-20 rounded-2xl' : 'rounded-2xl'}`}>
    <div className="mb-4 flex items-center justify-between"><button type="button" onClick={() => setView(new Date(view.getFullYear(), view.getMonth() - 1, 1))} className="flex h-9 w-9 items-center justify-center rounded-full text-slate-300 hover:bg-[#4E4F50]" aria-label="Previous month"><ChevronLeft className="h-4 w-4" /></button><span className="text-sm font-semibold text-slate-100">{new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(view)}</span><button type="button" onClick={() => setView(new Date(view.getFullYear(), view.getMonth() + 1, 1))} className="flex h-9 w-9 items-center justify-center rounded-full text-slate-300 hover:bg-[#4E4F50]" aria-label="Next month"><ChevronRight className="h-4 w-4" /></button></div>
    <div className="grid grid-cols-7 gap-1">{['Su','Mo','Tu','We','Th','Fr','Sa'].map((day) => <span key={day} className="py-1 text-center text-[10px] font-semibold text-slate-500">{day}</span>)}{days.map((day, index) => day == null ? <span key={`empty-${index}`} /> : (() => { const candidate = new Date(view.getFullYear(), view.getMonth(), day); const key = serialize(candidate); const active = selected && serialize(selected) === key; const unavailable = isBeforeMinimum(candidate); const isReference = key === referenceKey; return <button key={key} type="button" disabled={unavailable} aria-disabled={unavailable} aria-label={`${key}${isReference ? `, ${referenceLabel}` : ''}${unavailable ? ', unavailable' : ''}`} onClick={() => { onChange(key); setOpen(false); }} className={`relative mx-auto flex h-9 w-9 items-center justify-center rounded-full text-xs font-medium ${active ? 'bg-[#C7F33C] text-black' : unavailable ? 'cursor-not-allowed text-slate-600 line-through decoration-slate-600' : isReference ? 'border-2 border-[#C7F33C] bg-[#252728] text-slate-100' : key === today ? 'border border-[#C7F33C] text-slate-100' : 'text-slate-300 hover:bg-[#4E4F50]'}`}>{day}{isReference && !active && <span className="absolute -bottom-0.5 h-1 w-1 rounded-full bg-[#C7F33C]" />}</button>; })())}</div>
    {referenceKey && <div className="mt-3 flex items-center gap-2 border-t border-[#4E4F50] pt-3 text-xs text-slate-300"><span className="h-2 w-2 rounded-full bg-[#C7F33C]" /><span>{referenceLabel}: {new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric' }).format(parse(referenceKey)!)}</span></div>}
    <div className={`${referenceKey ? 'mt-2' : 'mt-3 border-t border-[#4E4F50] pt-3'} flex items-center justify-between`}>{allowClear ? <button type="button" onClick={() => { onChange(''); setOpen(false); }} className="text-xs font-medium text-slate-300 hover:text-white">Clear</button> : <span />}<div className="flex items-center gap-2"><button type="button" disabled={isBeforeMinimum(new Date())} onClick={() => { onChange(today); setOpen(false); }} className="rounded-lg px-3 py-2 text-xs font-medium text-[#C7F33C] hover:bg-[#4E4F50] disabled:cursor-not-allowed disabled:text-slate-600 disabled:hover:bg-transparent">Today</button>{mobile && <button type="button" onClick={() => setOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-full text-slate-400 hover:bg-[#4E4F50]" aria-label="Close"><X className="h-4 w-4" /></button>}</div></div>
  </div></>, document.body) : null;
  const display = selected ? new Intl.DateTimeFormat(undefined, { month: '2-digit', day: '2-digit', year: 'numeric' }).format(selected) : 'Select date';
  return <><button ref={buttonRef} type="button" disabled={disabled} onClick={() => setOpen((current) => !current)} aria-label={ariaLabel} aria-expanded={open} className="flex w-full items-center justify-between rounded-xl border border-[#4E4F50] bg-[#252728] px-3 py-2.5 text-sm text-slate-100 transition-colors hover:bg-[#303233] focus-visible:border-[#C7F33C] focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"><span className={selected ? '' : 'text-slate-500'}>{display}</span><CalendarDays className="h-4 w-4 text-slate-400" /></button>{panel}</>;
}
